package phenoscape.queries;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;

import phenoscape.queries.lib.PhenotypeExpression;
import phenoscape.queries.lib.Utils;

/**
 * This utility class holds the expected subsumption counts for phenotypes based on the test gene phenotype data 
 * file (phenotype_test_genes.txt in the phenoscape svn under trunk/data/test-files).  If this file changes, some these 
 * of these counts will certainly change (e.g., "quality") in addition to phenotypes being added/deleted.
 * @author peter
 *
 */
public class CountTableCheck {
	
	private final Map<String,Integer> contents = new HashMap<String,Integer>();
	private final Utils u;

	public CountTableCheck(Utils utils){
		u = utils;
		contents.put("count^OBO_REL:inheres_in_part_of(anatomical cluster)", 2);
		contents.put("count^OBO_REL:inheres_in_part_of(anatomical group)", 2);
		contents.put("count^OBO_REL:inheres_in_part_of(anatomical structure)", 2);
		contents.put("count^OBO_REL:inheres_in_part_of(anatomical system)", 2);
		contents.put("count^OBO_REL:inheres_in_part_of(body)", 2);
		contents.put("count^OBO_REL:inheres_in_part_of(bone)", 2);
		contents.put("count^OBO_REL:inheres_in_part_of(cranium)", 2);
		contents.put("count^OBO_REL:inheres_in_part_of(dermal bone)", 2);
		contents.put("count^OBO_REL:inheres_in_part_of(dermatocranium)", 2);
		contents.put("count^OBO_REL:inheres_in_part_of(dorsal hyoid arch)", 2);
		contents.put("count^OBO_REL:inheres_in_part_of(head)", 2);
		contents.put("count^OBO_REL:inheres_in_part_of(hyoid arch)", 2);
		contents.put("count^OBO_REL:inheres_in_part_of(intramembranous bone)", 2);
		contents.put("count^OBO_REL:inheres_in_part_of(material anatomical entity)", 2);
		contents.put("count^OBO_REL:inheres_in_part_of(multi-tissue structure)", 2);
		contents.put("count^OBO_REL:inheres_in_part_of(opercle)", 2);
		contents.put("count^OBO_REL:inheres_in_part_of(opercular flap)", 2);
		contents.put("count^OBO_REL:inheres_in_part_of(opercular series)", 2);
		contents.put("count^OBO_REL:inheres_in_part_of(organism subdivision)", 2);
		contents.put("count^OBO_REL:inheres_in_part_of(pharyngeal arch 2)", 2);
		contents.put("count^OBO_REL:inheres_in_part_of(pharyngeal arch)", 2);
		contents.put("count^OBO_REL:inheres_in_part_of(portion of connective tissue)", 2);
		contents.put("count^OBO_REL:inheres_in_part_of(portion of tissue)", 2);
		contents.put("count^OBO_REL:inheres_in_part_of(skeletal system)", 2);
		contents.put("count^OBO_REL:inheres_in_part_of(splanchnocranium)", 2);
		contents.put("count^OBO_REL:inheres_in_part_of(surface structure)", 2);
		contents.put("count^OBO_REL:inheres_in_part_of(suspensorium)", 2);
		contents.put("count^OBO_REL:inheres_in_part_of(teleost anatomical entity)", 2);
		contents.put("count", 2);
		contents.put("morphology^OBO_REL:inheres_in_part_of(anatomical cluster)", 4);
		contents.put("morphology^OBO_REL:inheres_in_part_of(anatomical group)", 8);
		contents.put("morphology^OBO_REL:inheres_in_part_of(anatomical region)", 3);
		contents.put("morphology^OBO_REL:inheres_in_part_of(anatomical structure)", 20);
		contents.put("morphology^OBO_REL:inheres_in_part_of(anatomical system)", 8);
		contents.put("morphology^OBO_REL:inheres_in_part_of(body)", 20);
		contents.put("morphology^OBO_REL:inheres_in_part_of(bone)", 4);
		contents.put("morphology^OBO_REL:inheres_in_part_of(brain)", 3);
		contents.put("morphology^OBO_REL:inheres_in_part_of(cavitated compound organ)", 4);
		contents.put("morphology^OBO_REL:inheres_in_part_of(central nervous system)", 3);
		contents.put("morphology^OBO_REL:inheres_in_part_of(cerebellum)", 3);
		contents.put("morphology^OBO_REL:inheres_in_part_of(compound organ)", 4);
		contents.put("morphology^OBO_REL:inheres_in_part_of(cranium)", 4);
		contents.put("morphology^OBO_REL:inheres_in_part_of(dermal bone)", 4);
		contents.put("morphology^OBO_REL:inheres_in_part_of(dermatocranium)", 4);
		contents.put("morphology^OBO_REL:inheres_in_part_of(dorsal hyoid arch)", 4);
		contents.put("morphology^OBO_REL:inheres_in_part_of(dorsal region of cerebellum)", 2);
		contents.put("morphology^OBO_REL:inheres_in_part_of(dorsal region)", 2);
		contents.put("morphology^OBO_REL:inheres_in_part_of(eye)", 1);
		contents.put("morphology^OBO_REL:inheres_in_part_of(fin)", 12);
		contents.put("morphology^OBO_REL:inheres_in_part_of(head)", 5);
		contents.put("morphology^OBO_REL:inheres_in_part_of(hindbrain)", 3);
		contents.put("morphology^OBO_REL:inheres_in_part_of(hyoid arch)", 4);
		contents.put("morphology^OBO_REL:inheres_in_part_of(intramembranous bone)", 4);
		contents.put("morphology^OBO_REL:inheres_in_part_of(material anatomical entity)", 20);
		contents.put("morphology^OBO_REL:inheres_in_part_of(multi-tissue structure)", 4);
		contents.put("morphology^OBO_REL:inheres_in_part_of(nervous system)", 4);
		contents.put("morphology^OBO_REL:inheres_in_part_of(opercle)", 4);
		contents.put("morphology^OBO_REL:inheres_in_part_of(opercular flap)", 4);
		contents.put("morphology^OBO_REL:inheres_in_part_of(opercular series)", 4);
		contents.put("morphology^OBO_REL:inheres_in_part_of(organism subdivision)", 17);
		contents.put("morphology^OBO_REL:inheres_in_part_of(paired fin)", 12);
		contents.put("morphology^OBO_REL:inheres_in_part_of(pectoral fin)", 12);
		contents.put("morphology^OBO_REL:inheres_in_part_of(pharyngeal arch 2)", 4);
		contents.put("morphology^OBO_REL:inheres_in_part_of(pharyngeal arch)", 4);
		contents.put("morphology^OBO_REL:inheres_in_part_of(portion of connective tissue)", 4);
		contents.put("morphology^OBO_REL:inheres_in_part_of(portion of tissue)", 4);
		contents.put("morphology^OBO_REL:inheres_in_part_of(sensory system)", 1);
		contents.put("morphology^OBO_REL:inheres_in_part_of(skeletal system)", 4);
		contents.put("morphology^OBO_REL:inheres_in_part_of(splanchnocranium)", 4);
		contents.put("morphology^OBO_REL:inheres_in_part_of(surface structure)", 17);
		contents.put("morphology^OBO_REL:inheres_in_part_of(suspensorium)", 4);
		contents.put("morphology^OBO_REL:inheres_in_part_of(teleost anatomical entity)", 20);
		contents.put("morphology^OBO_REL:inheres_in_part_of(ventral region of cerebellum)", 1);
		contents.put("morphology^OBO_REL:inheres_in_part_of(ventral region)", 1);
		contents.put("morphology^OBO_REL:inheres_in_part_of(visual system)", 1);
		contents.put("morphology", 20);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(anatomical cluster)", 5);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(anatomical group)", 9);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(anatomical region)", 3);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(anatomical structure)", 21);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(anatomical system)", 9);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(body)", 21);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(bone)", 5);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(brain)", 3);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(cavitated compound organ)", 4);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(central nervous system)", 3);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(cerebellum)", 3);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(compound organ)", 4);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(cranium)", 5);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(dermal bone)", 5);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(dermatocranium)", 5);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(dorsal hyoid arch)", 5);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(dorsal region of cerebellum)", 2);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(dorsal region)", 2);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(eye)", 1);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(fin)", 12);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(head)", 6);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(hindbrain)", 3);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(hyoid arch)", 5);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(intramembranous bone)", 5);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(material anatomical entity)", 21);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(multi-tissue structure)", 5);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(nervous system)", 4);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(opercle)", 5);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(opercular flap)", 5);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(opercular series)", 5);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(organism subdivision)", 18);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(paired fin)", 12);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(pectoral fin)", 12);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(pharyngeal arch 2)", 5);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(pharyngeal arch)", 5);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(portion of connective tissue)", 5);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(portion of tissue)", 5);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(sensory system)", 1);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(skeletal system)", 5);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(splanchnocranium)", 5);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(surface structure)", 18);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(suspensorium)", 5);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(teleost anatomical entity)", 21);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(ventral region of cerebellum)", 1);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(ventral region)", 1);
		contents.put("physical object quality^OBO_REL:inheres_in_part_of(visual system)", 1);
		contents.put("physical object quality", 21);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(anatomical cluster)", 1);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(anatomical group)", 1);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(anatomical structure)", 1);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(anatomical system)", 1);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(body)", 1);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(bone)", 1);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(cranium)", 1);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(dermal bone)", 1);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(dermatocranium)", 1);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(dorsal hyoid arch)", 1);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(head)", 1);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(hyoid arch)", 1);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(intramembranous bone)", 1);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(material anatomical entity)", 1);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(multi-tissue structure)", 1);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(opercle)", 1);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(opercular flap)", 1);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(opercular series)", 1);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(organism subdivision)", 1);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(pharyngeal arch 2)", 1);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(pharyngeal arch)", 1);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(portion of connective tissue)", 1);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(portion of tissue)", 1);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(skeletal system)", 1);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(splanchnocranium)", 1);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(surface structure)", 1);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(suspensorium)", 1);
		contents.put("physical quality^OBO_REL:inheres_in_part_of(teleost anatomical entity)", 1);
		contents.put("physical quality", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(anatomical cluster)", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(anatomical group)", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(anatomical structure)", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(anatomical system)", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(body)", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(bone)", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(cranium)", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(dermal bone)", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(dermatocranium)", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(dorsal hyoid arch)", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(head)", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(hyoid arch)", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(intramembranous bone)", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(material anatomical entity)", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(multi-tissue structure)", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(opercle)", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(opercular flap)", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(opercular series)", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(organism subdivision)", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(pharyngeal arch 2)", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(pharyngeal arch)", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(portion of connective tissue)", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(portion of tissue)", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(skeletal system)", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(splanchnocranium)", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(surface structure)", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(suspensorium)", 1);
		contents.put("position^OBO_REL:inheres_in_part_of(teleost anatomical entity)", 1);
		contents.put("position", 1);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(anatomical cluster)", 2);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(anatomical group)", 2);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(anatomical structure)", 2);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(anatomical system)", 2);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(body)", 2);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(bone)", 2);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(cranium)", 2);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(dermal bone)", 2);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(dermatocranium)", 2);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(dorsal hyoid arch)", 2);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(head)", 2);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(hyoid arch)", 2);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(intramembranous bone)", 2);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(material anatomical entity)", 2);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(multi-tissue structure)", 2);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(opercle)", 2);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(opercular flap)", 2);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(opercular series)", 2);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(organism subdivision)", 2);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(pharyngeal arch 2)", 2);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(pharyngeal arch)", 2);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(portion of connective tissue)", 2);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(portion of tissue)", 2);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(skeletal system)", 2);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(splanchnocranium)", 2);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(surface structure)", 2);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(suspensorium)", 2);
		contents.put("qualitative^OBO_REL:inheres_in_part_of(teleost anatomical entity)", 2);
		contents.put("qualitative", 2);
		contents.put("quality^OBO_REL:inheres_in_part_of(anatomical cluster)", 7);
		contents.put("quality^OBO_REL:inheres_in_part_of(anatomical group)", 11);
		contents.put("quality^OBO_REL:inheres_in_part_of(anatomical region)", 3);
		contents.put("quality^OBO_REL:inheres_in_part_of(anatomical structure)", 23);
		contents.put("quality^OBO_REL:inheres_in_part_of(anatomical system)", 11);
		contents.put("quality^OBO_REL:inheres_in_part_of(body)", 23);
		contents.put("quality^OBO_REL:inheres_in_part_of(bone)", 7);
		contents.put("quality^OBO_REL:inheres_in_part_of(brain)", 3);
		contents.put("quality^OBO_REL:inheres_in_part_of(cavitated compound organ)", 4);
		contents.put("quality^OBO_REL:inheres_in_part_of(central nervous system)", 3);
		contents.put("quality^OBO_REL:inheres_in_part_of(cerebellum)", 3);
		contents.put("quality^OBO_REL:inheres_in_part_of(compound organ)", 4);
		contents.put("quality^OBO_REL:inheres_in_part_of(cranium)", 7);
		contents.put("quality^OBO_REL:inheres_in_part_of(dermal bone)", 7);
		contents.put("quality^OBO_REL:inheres_in_part_of(dermatocranium)", 7);
		contents.put("quality^OBO_REL:inheres_in_part_of(dorsal hyoid arch)", 7);
		contents.put("quality^OBO_REL:inheres_in_part_of(dorsal region of cerebellum)", 2);
		contents.put("quality^OBO_REL:inheres_in_part_of(dorsal region)", 2);
		contents.put("quality^OBO_REL:inheres_in_part_of(eye)", 1);
		contents.put("quality^OBO_REL:inheres_in_part_of(fin)", 12);
		contents.put("quality^OBO_REL:inheres_in_part_of(head)", 8);
		contents.put("quality^OBO_REL:inheres_in_part_of(hindbrain)", 3);
		contents.put("quality^OBO_REL:inheres_in_part_of(hyoid arch)", 7);
		contents.put("quality^OBO_REL:inheres_in_part_of(intramembranous bone)", 7);
		contents.put("quality^OBO_REL:inheres_in_part_of(material anatomical entity)", 23);
		contents.put("quality^OBO_REL:inheres_in_part_of(multi-tissue structure)", 7);
		contents.put("quality^OBO_REL:inheres_in_part_of(nervous system)", 4);
		contents.put("quality^OBO_REL:inheres_in_part_of(opercle)", 7);
		contents.put("quality^OBO_REL:inheres_in_part_of(opercular flap)", 7);
		contents.put("quality^OBO_REL:inheres_in_part_of(opercular series)", 7);
		contents.put("quality^OBO_REL:inheres_in_part_of(organism subdivision)", 20);
		contents.put("quality^OBO_REL:inheres_in_part_of(paired fin)", 12);
		contents.put("quality^OBO_REL:inheres_in_part_of(pectoral fin)", 12);
		contents.put("quality^OBO_REL:inheres_in_part_of(pharyngeal arch 2)", 7);
		contents.put("quality^OBO_REL:inheres_in_part_of(pharyngeal arch)", 7);
		contents.put("quality^OBO_REL:inheres_in_part_of(portion of connective tissue)", 7);
		contents.put("quality^OBO_REL:inheres_in_part_of(portion of tissue)", 7);
		contents.put("quality^OBO_REL:inheres_in_part_of(sensory system)", 1);
		contents.put("quality^OBO_REL:inheres_in_part_of(skeletal system)", 7);
		contents.put("quality^OBO_REL:inheres_in_part_of(splanchnocranium)", 7);
		contents.put("quality^OBO_REL:inheres_in_part_of(surface structure)", 20);
		contents.put("quality^OBO_REL:inheres_in_part_of(suspensorium)", 7);
		contents.put("quality^OBO_REL:inheres_in_part_of(teleost anatomical entity)", 23);
		contents.put("quality^OBO_REL:inheres_in_part_of(ventral region of cerebellum)", 1);
		contents.put("quality^OBO_REL:inheres_in_part_of(ventral region)", 1);
		contents.put("quality^OBO_REL:inheres_in_part_of(visual system)", 1);
		contents.put("quality", 23);
		contents.put("shape^OBO_REL:inheres_in_part_of(anatomical cluster)", 3);
		contents.put("shape^OBO_REL:inheres_in_part_of(anatomical group)", 4);
		contents.put("shape^OBO_REL:inheres_in_part_of(anatomical region)", 1);
		contents.put("shape^OBO_REL:inheres_in_part_of(anatomical structure)", 4);
		contents.put("shape^OBO_REL:inheres_in_part_of(anatomical system)", 4);
		contents.put("shape^OBO_REL:inheres_in_part_of(body)", 4);
		contents.put("shape^OBO_REL:inheres_in_part_of(bone)", 3);
		contents.put("shape^OBO_REL:inheres_in_part_of(brain)", 1);
		contents.put("shape^OBO_REL:inheres_in_part_of(cavitated compound organ)", 1);
		contents.put("shape^OBO_REL:inheres_in_part_of(central nervous system)", 1);
		contents.put("shape^OBO_REL:inheres_in_part_of(cerebellum)", 1);
		contents.put("shape^OBO_REL:inheres_in_part_of(compound organ)", 1);
		contents.put("shape^OBO_REL:inheres_in_part_of(cranium)", 3);
		contents.put("shape^OBO_REL:inheres_in_part_of(dermal bone)", 3);
		contents.put("shape^OBO_REL:inheres_in_part_of(dermatocranium)", 3);
		contents.put("shape^OBO_REL:inheres_in_part_of(dorsal hyoid arch)", 3);
		contents.put("shape^OBO_REL:inheres_in_part_of(dorsal region of cerebellum)", 1);
		contents.put("shape^OBO_REL:inheres_in_part_of(dorsal region)", 1);
		contents.put("shape^OBO_REL:inheres_in_part_of(eye)", 0);
		contents.put("shape^OBO_REL:inheres_in_part_of(head)", 3);
		contents.put("shape^OBO_REL:inheres_in_part_of(hindbrain)", 1);
		contents.put("shape^OBO_REL:inheres_in_part_of(hyoid arch)", 3);
		contents.put("shape^OBO_REL:inheres_in_part_of(intramembranous bone)", 3);
		contents.put("shape^OBO_REL:inheres_in_part_of(material anatomical entity)", 4);
		contents.put("shape^OBO_REL:inheres_in_part_of(multi-tissue structure)", 3);
		contents.put("shape^OBO_REL:inheres_in_part_of(nervous system)", 1);
		contents.put("shape^OBO_REL:inheres_in_part_of(opercle)", 3);
		contents.put("shape^OBO_REL:inheres_in_part_of(opercular flap)", 3);
		contents.put("shape^OBO_REL:inheres_in_part_of(opercular series)", 3);
		contents.put("shape^OBO_REL:inheres_in_part_of(organism subdivision)", 3);
		contents.put("shape^OBO_REL:inheres_in_part_of(pharyngeal arch 2)", 3);
		contents.put("shape^OBO_REL:inheres_in_part_of(pharyngeal arch)", 3);
		contents.put("shape^OBO_REL:inheres_in_part_of(portion of connective tissue)", 3);
		contents.put("shape^OBO_REL:inheres_in_part_of(portion of tissue)", 3);
		contents.put("shape^OBO_REL:inheres_in_part_of(sensory system)", 0);
		contents.put("shape^OBO_REL:inheres_in_part_of(skeletal system)", 3);
		contents.put("shape^OBO_REL:inheres_in_part_of(splanchnocranium)", 3);
		contents.put("shape^OBO_REL:inheres_in_part_of(surface structure)", 3);
		contents.put("shape^OBO_REL:inheres_in_part_of(suspensorium)", 3);
		contents.put("shape^OBO_REL:inheres_in_part_of(teleost anatomical entity)", 4);
		contents.put("shape^OBO_REL:inheres_in_part_of(ventral region of cerebellum)", 0);
		contents.put("shape^OBO_REL:inheres_in_part_of(ventral region)", 0);
		contents.put("shape^OBO_REL:inheres_in_part_of(visual system)", 0);
		contents.put("shape", 4);
		contents.put("size^OBO_REL:inheres_in_part_of(anatomical group)", 3);
		contents.put("size^OBO_REL:inheres_in_part_of(anatomical region)", 2);
		contents.put("size^OBO_REL:inheres_in_part_of(anatomical structure)", 15);
		contents.put("size^OBO_REL:inheres_in_part_of(anatomical system)", 3);
		contents.put("size^OBO_REL:inheres_in_part_of(body)", 15);
		contents.put("size^OBO_REL:inheres_in_part_of(brain)", 2);
		contents.put("size^OBO_REL:inheres_in_part_of(cavitated compound organ)", 3);
		contents.put("size^OBO_REL:inheres_in_part_of(central nervous system)", 2);
		contents.put("size^OBO_REL:inheres_in_part_of(cerebellum)", 2);
		contents.put("size^OBO_REL:inheres_in_part_of(compound organ)", 3);
		contents.put("size^OBO_REL:inheres_in_part_of(dorsal region of cerebellum)", 1);
		contents.put("size^OBO_REL:inheres_in_part_of(dorsal region)", 1);
		contents.put("size^OBO_REL:inheres_in_part_of(eye)", 1);
		contents.put("size^OBO_REL:inheres_in_part_of(fin)", 12);
		contents.put("size^OBO_REL:inheres_in_part_of(head)", 1);
		contents.put("size^OBO_REL:inheres_in_part_of(hindbrain)", 2);
		contents.put("size^OBO_REL:inheres_in_part_of(material anatomical entity)", 15);
		contents.put("size^OBO_REL:inheres_in_part_of(nervous system)", 3);
		contents.put("size^OBO_REL:inheres_in_part_of(organism subdivision)", 13);
		contents.put("size^OBO_REL:inheres_in_part_of(paired fin)", 12);
		contents.put("size^OBO_REL:inheres_in_part_of(pectoral fin)", 12);
		contents.put("size^OBO_REL:inheres_in_part_of(sensory system)", 1);
		contents.put("size^OBO_REL:inheres_in_part_of(surface structure)", 13);
		contents.put("size^OBO_REL:inheres_in_part_of(teleost anatomical entity)", 15);
		contents.put("size^OBO_REL:inheres_in_part_of(ventral region of cerebellum)", 1);
		contents.put("size^OBO_REL:inheres_in_part_of(ventral region)", 1);
		contents.put("size^OBO_REL:inheres_in_part_of(visual system)", 1);
		contents.put("size", 15);
		contents.put("texture^OBO_REL:inheres_in_part_of(anatomical cluster)", 1);
		contents.put("texture^OBO_REL:inheres_in_part_of(anatomical group)", 1);
		contents.put("texture^OBO_REL:inheres_in_part_of(anatomical structure)", 1);
		contents.put("texture^OBO_REL:inheres_in_part_of(anatomical system)", 1);
		contents.put("texture^OBO_REL:inheres_in_part_of(body)", 1);
		contents.put("texture^OBO_REL:inheres_in_part_of(bone)", 1);
		contents.put("texture^OBO_REL:inheres_in_part_of(cranium)", 1);
		contents.put("texture^OBO_REL:inheres_in_part_of(dermal bone)", 1);
		contents.put("texture^OBO_REL:inheres_in_part_of(dermatocranium)", 1);
		contents.put("texture^OBO_REL:inheres_in_part_of(dorsal hyoid arch)", 1);
		contents.put("texture^OBO_REL:inheres_in_part_of(head)", 1);
		contents.put("texture^OBO_REL:inheres_in_part_of(hyoid arch)", 1);
		contents.put("texture^OBO_REL:inheres_in_part_of(intramembranous bone)", 1);
		contents.put("texture^OBO_REL:inheres_in_part_of(material anatomical entity)", 1);
		contents.put("texture^OBO_REL:inheres_in_part_of(multi-tissue structure)", 1);
		contents.put("texture^OBO_REL:inheres_in_part_of(opercle)", 1);
		contents.put("texture^OBO_REL:inheres_in_part_of(opercular flap)", 1);
		contents.put("texture^OBO_REL:inheres_in_part_of(opercular series)", 1);
		contents.put("texture^OBO_REL:inheres_in_part_of(organism subdivision)", 1);
		contents.put("texture^OBO_REL:inheres_in_part_of(pharyngeal arch 2)", 1);
		contents.put("texture^OBO_REL:inheres_in_part_of(pharyngeal arch)", 1);
		contents.put("texture^OBO_REL:inheres_in_part_of(portion of connective tissue)", 1);
		contents.put("texture^OBO_REL:inheres_in_part_of(portion of tissue)", 1);
		contents.put("texture^OBO_REL:inheres_in_part_of(skeletal system)", 1);
		contents.put("texture^OBO_REL:inheres_in_part_of(splanchnocranium)", 1);
		contents.put("texture^OBO_REL:inheres_in_part_of(surface structure)", 1);
		contents.put("texture^OBO_REL:inheres_in_part_of(suspensorium)", 1);
		contents.put("texture^OBO_REL:inheres_in_part_of(teleost anatomical entity)", 1);
		contents.put("texture", 1);

	}
	
	public int get(PhenotypeExpression e) throws SQLException{
		return contents.get(e.getFullName(u)).intValue();
	}
	
	public boolean hasPhenotype(PhenotypeExpression e) throws SQLException{
		return contents.containsKey(e.getFullName(u));
	}
}
